In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [12]:
x = np.array([5, 15, 25, 35, 45, 55])
y = np.array([5, 20, 14, 32, 22, 38])
print (f'x : {x}')
print (f'y: {y}')
# make it into a col array
x = x.reshape((-1, 1))
print(x)

x : [ 5 15 25 35 45 55]
y: [ 5 20 14 32 22 38]
[[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]]


In [11]:
model = LinearRegression().fit(x, y)
print('intercept:', model.intercept_)
print('slope:', model.coef_)

r_sq = model.score(x, y)
print('coefficient of determination:', r_sq)

y_pred = model.predict(x)
print('predicted response:', y_pred, sep='\n')

y_pred = model.intercept_ + model.coef_ * x
print('predicted response:', y_pred, sep='\n')

x_new = np.arange(5)
print ('x_new :', x_new)
x_new = x_new.reshape((-1, 1))
y_new = model.predict(x_new)
print('predicted y_new: ', y_new)

intercept: 5.633333333333329
slope: [0.54]
coefficient of determination: 0.715875613747954
predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]
predicted response:
[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]
x_new : [0 1 2 3 4]
predicted y_new:  [5.63333333 6.17333333 6.71333333 7.25333333 7.79333333]
