In [2]:
# load coo_matrix from Scipy.sparse module
from scipy.sparse import coo_matrix
# import numpy
import numpy as np

https://cmdlinetips.com/2019/01/3-ways-to-create-sparse-matrix-in-coo-format-with-scipy/

In [3]:
# create empty COO matrix
A = coo_matrix((4, 5))
display(A) # prints nothing
# use these to print
display(A.toarray())
display(A.todense())

<4x5 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in COOrdinate format>

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

matrix([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [25]:
# Constructing a matrix using ijv format
row  = np.array([0, 3, 1, 2, 3, 2])
col  = np.array([0, 1, 1, 2, 0, 1])
data = np.array([10, 3, 88, 9, 2,6])

B = coo_matrix((data, (row, col)), shape = (4,4))
print (coo_matrix((data, (row, col))).shape[1])

# what is this displaying ???
print (B)
display(B.toarray())


3
  (0, 0)	10
  (3, 1)	3
  (1, 1)	88
  (2, 2)	9
  (3, 0)	2
  (2, 1)	6


array([[10,  0,  0,  0],
       [ 0, 88,  0,  0],
       [ 0,  6,  9,  0],
       [ 2,  3,  0,  0]])

In [29]:
# accessing elements.
# Use A.toarray()[i, j]
print (B.toarray().shape)
print (B.toarray()[0,0])

(4, 4)
10
